### ISSUE TITLE
Differences vs pytest?

### ISSUE THREAD

**Issue by wrabit** [adamchainz/unittest-parametrize#108]
"The API mirrors @pytest... _as much as possible_"

What are the main differences in this and pytests parameterize? Do we lose/gain any functionality?

**Comment by adamchainz** [comment]
I think you'll find it's basically the same. I don't really have the time to write a comparison section, but I'd be open to a PR with one. Maybe an LLM fed with both documentation pages can produce a reasonable comparison?
