### ISSUE TITLE
More information against `unittest.TestCase.subTest` in README

### ISSUE THREAD

**Issue by souliane** [adamchainz/unittest-parametrize#99]
### Description

This is a suggestion to add some information to the [section](https://github.com/adamchainz/unittest-parametrize?tab=readme-ov-file#why-not-subtests) that arguments against `unittest.TestCase.subTest`, at the end of the README.

You could add that, when tests are run with pytest and a `subTest` fails, the failure report does not event allow to identify which subtest failed.

Also, pytest officially states that `subTest` is not supported [here](https://docs.pytest.org/en/4.6.x/unittest.html?highlight=subtests).

**Comment by adamchainz** [comment]
Thanks for the idea!

You linked an old version of the pyetst docs page. The [latest versionhttps://docs.pytest.org/en/latest/how-to/unittest.html) says only that subtests require pytest-subtest.

I think I won’t mention it then, since it's not such a strong argument.
